# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: predict.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rpredict.proto\"@\n\x11PredictionRequest\x12\r\n\x05image\x18\x01 \x01(\x0c\x12\r\n\x05shape\x18\x02 \x01(\t\x12\r\n\x05top_n\x18\x03 \x01(\x05\"%\n\x12PredictionResponse\x12\x0f\n\x07message\x18\x01 \x01(\t2I\n\x11PredictionService\x12\x34\n\x07predict\x12\x12.PredictionRequest\x1a\x13.PredictionResponse\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'predict_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PREDICTIONREQUEST._serialized_start=17
  _PREDICTIONREQUEST._serialized_end=81
  _PREDICTIONRESPONSE._serialized_start=83
  _PREDICTIONRESPONSE._serialized_end=120
  _PREDICTIONSERVICE._serialized_start=122
  _PREDICTIONSERVICE._serialized_end=195
# @@protoc_insertion_point(module_scope)
